select * from Carros;

SELECT VIEW_NAME 
FROM USER_VIEWS;

select * from SOMA_VALOR_CARRO;
SELECT * FROM MEDIA_VALOR_CARRO;
SELECT * FROM CARROS_ORDENADOS_POR_PRECO;


CREATE TABLE IPVA (
    ID_CARRO NUMBER,
    ANO_REFERENCIA NUMBER(4),
    VALOR_IPVA NUMBER(10,2),
    PAGO CHAR(1),
    CONSTRAINT FK_CARRO FOREIGN KEY (ID_CARRO) REFERENCES Carros(ID_CARRO)
);

SELECT * FROM IPVA;


SELECT 
  C.ID_CARRO,
  C.MARCA,
  C.MODELO,
  C.PRECO,
  ROUND(C.PRECO * 0.04, 2) AS VALOR_IPVA
FROM CARROS C;



INSERT INTO IPVA (ID_IPVA, ID_CARRO, ANO_REFERENCIA, VALOR, PAGO)
SELECT 
    1,                         -- ID_IPVA (altere conforme necessário)
    C.ID_CARRO,
    2025,                      -- Ano de referência
    ROUND(C.PRECO * 0.04, 2),  -- 4% do preço do carro
    'N'
FROM CARROS C
WHERE C.ID_CARRO = 101;


INSERT INTO IPVA (ID_IPVA, ID_CARRO, ANO_REFERENCIA, VALOR, PAGO)
SELECT 
    ROWNUM,                   -- ID_IPVA gerado automaticamente com ROWNUM
    C.ID_CARRO,
    2025,
    ROUND(C.PRECO * 0.04, 2),
    'N'
FROM CARROS C;


SELECT * FROM IPVA;

UPDATE
SET
WHERE 

CREATE TABLE ESTILOS (
  ID_CARRO NUMBER,
  CATEGORIA VARCHAR2(30),
  CONSTRAINT FK_ESTILO FOREIGN KEY (ID_CARRO) REFERENCES CARROS(ID_CARRO)
);

(
SELECT * FROM Carros;

UPDATE Carros SET ESTILO = 'Sedan' WHERE ID_CARRO IN (1, 2, 3, 10, 11, 12, 13, 14, 15, 16, 20, 25, 27, 34, 35, 36, 38, 39, 40, 45, 46, 47, 48, 50, 54, 55, 60, 62, 65, 66, 67, 69, 72, 74, 75, 76, 78, 79, 80, 84, 85, 86, 88, 89, 94, 95, 98);


desc Carros;
select * from Carros


ALTER TABLE Carros ADD ESTILO VARCHAR2(20);
)
(
UPDATE Carros SET ESTILO = 'SUV' WHERE ID_CARRO IN(19,22,30,33,34,36,37,38,42,44,49,54,62,69,70,72,82,90,92,93,94,95,96,99);

UPDATE Carros SET ESTILO = 'HATCH' WHERE ID_CARRO IN(4,6,7,8,9,13,16,18,24,28,31,35,41,50,51,52,53,57,58,59,61,66,68,71,73,77,83,84,87);

UPDATE Carros SET ESTILO = 'PICAPE' WHERE ID_CARRO IN (23,24,36,41,43,44,63,91,97);

UPDATE Carros SET ESTILO = 'MINIVAN' WHERE ID_CARRO IN(48,71,98);

UPDATE Carros SET ESTILO = 'ESPORTIVO' WHERE ID_CARRO IN(54,56,75,85,92);

SELECT * FROM Carros;

UPDATE Carros SET ESTILO = 'sedan' WHERE ID_CARRO IN(17,55,74,78,81,86);
)
create table INDENTIFICACAO (
 ID_CARRO NUMBER,
 PLACA varchar(7) NOT NULL , 
 CONSTRAINT FK_INDENTIFICACAO FOREIGN KEY (ID_CARRO) REFERENCES CARROS(ID_CARRO)
);
(
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA)
 VALUES (1, 'ADR5L06');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA)
 VALUES (2, 'AEY9U63');
INSERT INTO INDENTIFICACAO(ID_CARRO, PLACA) 
VALUES (3, 'AIP5Y02');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA)
 VALUES (4, 'AOV5O42');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) 
VALUES (5, 'ARS5X20');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) 
VALUES (6, 'ASA3K96');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA
) VALUES (7, 'AUQ3H16');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA)
 VALUES (8, 'BJV3P84');
INSERT INTO INDENTIFICACAO(ID_CARRO, PLACA
) VALUES (9, 'BPD9R15');
INSERT INTO INDENTIFICACAO(ID_CARRO, PLACA)
 VALUES (10, 'BVP6T51');
INSERT INTO INDENTIFICACAO(ID_CARRO, PLACA)
 VALUES (11, 'EFRG5R8');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) 
VALUES (12, 'ASFV5R8');
INSERT INTO INDENTIFICACAO(ID_CARRO, PLACA)
 VALUES (13, 'NAJW6B2');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA)
 VALUES (14, 'SBIE9L4');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA)
 VALUES (15, 'GQRS1H6');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA)
 VALUES (16, 'AYSA3K9');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA)
 VALUES (17, 'ENTG9Q2');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA)
 VALUES (18, 'TGHU0U4');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA)
 VALUES (19, 'BYJH8P2');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(20, 'VSEW0Ç8');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES  
(  21, 'CETJ6M7');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(22, 'VQQA8R3');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(23, 'VXQY0B9');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(24, 'MSGT5U9');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(25, 'PLRT5M9');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(26, 'MJTN6B4');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(27, 'YMAE2L5');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(29, 'AMRT6M5');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(30, 'ANU0U89');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (31, 'BCQ0L77');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES 
(32, 'CUT6J17');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(33, 'CZQ1Z81');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(34, 'DBO0U94');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (35, 'DMO2K59');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(36, 'DTR1D86');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(37, 'DUH4Q69');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(38, 'EAY8N49');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (39, 'ELV9D87');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (40, 'GCX1W32');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (41, 'GVM5S81');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(42, 'GVZ5L12');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(43, 'HAD2U31');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (44, 'HLM1Q67');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (45, 'HOR7L47');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (46, 'HLM1Q67');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(47, 'HOR7L47');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(48, 'HSE7R30');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(49, 'IAV1V40');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(50, 'IBK6Z29');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES 
(51, 'ICU7T53');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(52, 'IDF1U85');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (53, 'IFK2W03');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(54, 'IHN8N45');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(55, 'ILR7A94');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (56, 'IQP9E22');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (57, 'IWT3X50');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(58, 'JBE9M79');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(59, 'JCO2F88');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (60, 'JPL0T95');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (61, 'KDR4S61');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(62, 'KJU7R10');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES 
(63, 'KLW6B66');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (64, 'KRC5X73');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (65, 'KUM2H12');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (66, 'KYZ1V19');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(67, 'LAV8C83');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(68, 'LDN4T26');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (69, 'LIE6R09');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(70, 'LQL2M97');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (71, 'LRW5K48');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES 
(72, 'LVG1Z06');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(73, 'MAJ9U77');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (74, 'MBO8Y84');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (75, 'MNS7D18');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(76, 'MQK3P34');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(77, 'MRZ5G91');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(78, 'MVI6J61');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(79, 'NAU1L13');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (80, 'NBK4A70');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (81, 'NCJ3S58');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (82, 'NEU6T99');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (83, 'NPO9R22');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(84, 'NRM7F88');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (85, 'NVL5W55');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (86, 'NYF3Z40');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES 
(87, 'OAB8X74');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (88, 'OCU1H83');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(89, 'ODT9K52');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES 
(90, 'OEN0M33');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(91, 'OFW7T06');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (92, 'OLM6J21');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (93, 'OPX2V60');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (94, 'OUI4G48');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (95, 'PBA3E73');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (96, 'PCD2H91');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(97, 'PHL0U38');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
(98, 'PQY6Z02');
INSERT INTO INDENTIFICACAO (ID_CARRO, PLACA) VALUES
 (99, 'PXV5A19');
)


SELECT C.ID_CARRO, C.MARCA, C.MODELO, I.PLACA
FROM CARROS C
JOIN INDENTIFICACAO I ON C.ID_CARRO = I.ID_CARRO;

SELECT * FROM INDENTIFICACAO;
SELECT * FROM CARROS ;


alter table CARROS
ADD COD_DETRAN VARCHAR2(20); 



UPDATE CARROS SET COD_DETRAN = 'SP123456' WHERE ID_CARRO = 1;
UPDATE CARROS SET COD_DETRAN = 'RJ789101' WHERE ID_CARRO = 2;
-- e assim por diante


SELECT ID_CARRO, MARCA, MODELO, COD_DETRAN
FROM CARROS
WHERE COD_DETRAN IS NOT NULL;


SELECT * FROM CARROS;


(
UPDATE CARROS SET COD_DETRAN = 'PR724902' WHERE ID_CARRO = 3;
UPDATE CARROS SET COD_DETRAN = 'BA156960' WHERE ID_CARRO = 4;
UPDATE CARROS SET COD_DETRAN = 'PR236404' WHERE ID_CARRO = 5;
UPDATE CARROS SET COD_DETRAN = 'GO325903' WHERE ID_CARRO = 6;
UPDATE CARROS SET COD_DETRAN = 'PE314948' WHERE ID_CARRO = 7;
UPDATE CARROS SET COD_DETRAN = 'RS743131' WHERE ID_CARRO = 8;
UPDATE CARROS SET COD_DETRAN = 'SC780715' WHERE ID_CARRO = 9;
UPDATE CARROS SET COD_DETRAN = 'PE591789' WHERE ID_CARRO = 10;
UPDATE CARROS SET COD_DETRAN = 'GO346910' WHERE ID_CARRO = 11;
UPDATE CARROS SET COD_DETRAN = 'GO843497' WHERE ID_CARRO = 12;
UPDATE CARROS SET COD_DETRAN = 'SP025831' WHERE ID_CARRO = 13;
UPDATE CARROS SET COD_DETRAN = 'PE290054' WHERE ID_CARRO = 14;
UPDATE CARROS SET COD_DETRAN = 'MG495960' WHERE ID_CARRO = 15;
UPDATE CARROS SET COD_DETRAN = 'RS283316' WHERE ID_CARRO = 16;
UPDATE CARROS SET COD_DETRAN = 'BA817177' WHERE ID_CARRO = 17;
UPDATE CARROS SET COD_DETRAN = 'RJ316932' WHERE ID_CARRO = 18;
UPDATE CARROS SET COD_DETRAN = 'BA483614' WHERE ID_CARRO = 19;
UPDATE CARROS SET COD_DETRAN = 'BA243524' WHERE ID_CARRO = 20;
UPDATE CARROS SET COD_DETRAN = 'CE972352' WHERE ID_CARRO = 21;
UPDATE CARROS SET COD_DETRAN = 'RJ284371' WHERE ID_CARRO = 22;
UPDATE CARROS SET COD_DETRAN = 'BA717373' WHERE ID_CARRO = 23;
UPDATE CARROS SET COD_DETRAN = 'PR398995' WHERE ID_CARRO = 24;
UPDATE CARROS SET COD_DETRAN = 'PR159399' WHERE ID_CARRO = 25;
UPDATE CARROS SET COD_DETRAN = 'SC384050' WHERE ID_CARRO = 26;
UPDATE CARROS SET COD_DETRAN = 'PE454989' WHERE ID_CARRO = 27;
UPDATE CARROS SET COD_DETRAN = 'MG940210' WHERE ID_CARRO = 28;
UPDATE CARROS SET COD_DETRAN = 'PR565334' WHERE ID_CARRO = 29;
UPDATE CARROS SET COD_DETRAN = 'SC489545' WHERE ID_CARRO = 30;
UPDATE CARROS SET COD_DETRAN = 'SP752695' WHERE ID_CARRO = 31;
UPDATE CARROS SET COD_DETRAN = 'GO561824' WHERE ID_CARRO = 32;
UPDATE CARROS SET COD_DETRAN = 'PR895452' WHERE ID_CARRO = 33;
UPDATE CARROS SET COD_DETRAN = 'SC813651' WHERE ID_CARRO = 34;
UPDATE CARROS SET COD_DETRAN = 'SC629772' WHERE ID_CARRO = 35;
UPDATE CARROS SET COD_DETRAN = 'SP044335' WHERE ID_CARRO = 36;
UPDATE CARROS SET COD_DETRAN = 'MG750337' WHERE ID_CARRO = 37;
UPDATE CARROS SET COD_DETRAN = 'RJ983863' WHERE ID_CARRO = 38;
UPDATE CARROS SET COD_DETRAN = 'PR361624' WHERE ID_CARRO = 39;
UPDATE CARROS SET COD_DETRAN = 'SC468876' WHERE ID_CARRO = 40;
UPDATE CARROS SET COD_DETRAN = 'SP254895' WHERE ID_CARRO = 41;
UPDATE CARROS SET COD_DETRAN = 'PR603193' WHERE ID_CARRO = 42;
UPDATE CARROS SET COD_DETRAN = 'GO448243' WHERE ID_CARRO = 43;
UPDATE CARROS SET COD_DETRAN = 'RS503105' WHERE ID_CARRO = 44;
UPDATE CARROS SET COD_DETRAN = 'SC058081' WHERE ID_CARRO = 45;
UPDATE CARROS SET COD_DETRAN = 'PR527712' WHERE ID_CARRO = 46;
UPDATE CARROS SET COD_DETRAN = 'MG702349' WHERE ID_CARRO = 47;
UPDATE CARROS SET COD_DETRAN = 'MG780408' WHERE ID_CARRO = 48;
UPDATE CARROS SET COD_DETRAN = 'PE045651' WHERE ID_CARRO = 49;
UPDATE CARROS SET COD_DETRAN = 'GO492025' WHERE ID_CARRO = 50;
UPDATE CARROS SET COD_DETRAN = 'SP483920' WHERE ID_CARRO = 51;
UPDATE CARROS SET COD_DETRAN = 'MG928415' WHERE ID_CARRO = 52;
UPDATE CARROS SET COD_DETRAN = 'RJ370512' WHERE ID_CARRO = 53;
UPDATE CARROS SET COD_DETRAN = 'BA650194' WHERE ID_CARRO = 54;
UPDATE CARROS SET COD_DETRAN = 'RS185630' WHERE ID_CARRO = 55;
UPDATE CARROS SET COD_DETRAN = 'PR906781' WHERE ID_CARRO = 56;
UPDATE CARROS SET COD_DETRAN = 'SC237460' WHERE ID_CARRO = 57;
UPDATE CARROS SET COD_DETRAN = 'PE738904' WHERE ID_CARRO = 58;
UPDATE CARROS SET COD_DETRAN = 'CE814256' WHERE ID_CARRO = 59;
UPDATE CARROS SET COD_DETRAN = 'GO129075' WHERE ID_CARRO = 60;
UPDATE CARROS SET COD_DETRAN = 'SP574839' WHERE ID_CARRO = 61;
UPDATE CARROS SET COD_DETRAN = 'MG405812' WHERE ID_CARRO = 62;
UPDATE CARROS SET COD_DETRAN = 'RJ920348' WHERE ID_CARRO = 63;
UPDATE CARROS SET COD_DETRAN = 'BA730154' WHERE ID_CARRO = 64;
UPDATE CARROS SET COD_DETRAN = 'RS618209' WHERE ID_CARRO = 65;
UPDATE CARROS SET COD_DETRAN = 'PR859704' WHERE ID_CARRO = 66;
UPDATE CARROS SET COD_DETRAN = 'SC740681' WHERE ID_CARRO = 67;
UPDATE CARROS SET COD_DETRAN = 'PE312970' WHERE ID_CARRO = 68;
UPDATE CARROS SET COD_DETRAN = 'CE914028' WHERE ID_CARRO = 69;
UPDATE CARROS SET COD_DETRAN = 'GO153287' WHERE ID_CARRO = 70;
UPDATE CARROS SET COD_DETRAN = 'SP207419' WHERE ID_CARRO = 71;
UPDATE CARROS SET COD_DETRAN = 'MG581640' WHERE ID_CARRO = 72;
UPDATE CARROS SET COD_DETRAN = 'RJ849512' WHERE ID_CARRO = 73;
UPDATE CARROS SET COD_DETRAN = 'BA360975' WHERE ID_CARRO = 74;
UPDATE CARROS SET COD_DETRAN = 'RS148709' WHERE ID_CARRO = 75;
UPDATE CARROS SET COD_DETRAN = 'PR923684' WHERE ID_CARRO = 76;
UPDATE CARROS SET COD_DETRAN = 'SC436750' WHERE ID_CARRO = 77;
UPDATE CARROS SET COD_DETRAN = 'PE591027' WHERE ID_CARRO = 78;
UPDATE CARROS SET COD_DETRAN = 'CE703591' WHERE ID_CARRO = 79;
UPDATE CARROS SET COD_DETRAN = 'GO872153' WHERE ID_CARRO = 80;
UPDATE CARROS SET COD_DETRAN = 'SP364280' WHERE ID_CARRO = 81;
UPDATE CARROS SET COD_DETRAN = 'MG728145' WHERE ID_CARRO = 82;
UPDATE CARROS SET COD_DETRAN = 'RJ514903' WHERE ID_CARRO = 83;
UPDATE CARROS SET COD_DETRAN = 'BA694185' WHERE ID_CARRO = 84;
UPDATE CARROS SET COD_DETRAN = 'RS384207' WHERE ID_CARRO = 85;
UPDATE CARROS SET COD_DETRAN = 'PR978305' WHERE ID_CARRO = 86;
UPDATE CARROS SET COD_DETRAN = 'SC680145' WHERE ID_CARRO = 87;
UPDATE CARROS SET COD_DETRAN = 'PE803724' WHERE ID_CARRO = 88;
UPDATE CARROS SET COD_DETRAN = 'CE914573' WHERE ID_CARRO = 89;
UPDATE CARROS SET COD_DETRAN = 'GO193846' WHERE ID_CARRO = 90;
UPDATE CARROS SET COD_DETRAN = 'SP548701' WHERE ID_CARRO = 91;
UPDATE CARROS SET COD_DETRAN = 'MG316982' WHERE ID_CARRO = 92;
UPDATE CARROS SET COD_DETRAN = 'RJ709248' WHERE ID_CARRO = 93;
UPDATE CARROS SET COD_DETRAN = 'BA942315' WHERE ID_CARRO = 94;
UPDATE CARROS SET COD_DETRAN = 'RS170693' WHERE ID_CARRO = 95;
UPDATE CARROS SET COD_DETRAN = 'PR625389' WHERE ID_CARRO = 96;
UPDATE CARROS SET COD_DETRAN = 'SC718054' WHERE ID_CARRO = 97;
UPDATE CARROS SET COD_DETRAN = 'PE206379' WHERE ID_CARRO = 98;
UPDATE CARROS SET COD_DETRAN = 'CE983207' WHERE ID_CARRO = 99;
UPDATE CARROS SET COD_DETRAN = 'GO419837' WHERE ID_CARRO = 100;
)
 SELECT * FROM CARROS;
 
 
 ALTER TABLE CARROS
ADD STATUS VARCHAR2(20);


UPDATE CARROS SET STATUS = 'Disponível' WHERE ID_CARRO BETWEEN 1 AND 30;
UPDATE CARROS SET STATUS = 'Vendido' WHERE ID_CARRO BETWEEN 31 AND 60;
UPDATE CARROS SET STATUS = 'Em manutenção' WHERE ID_CARRO BETWEEN 61 AND 90;
UPDATE CARROS SET STATUS = 'Disponível' WHERE ID_CARRO > 90;


CREATE TABLE STATUS_CARRO (
  ID_CARRO NUMBER,
  STATUS VARCHAR2(20),
  CONSTRAINT FK_STATUS_CARRO FOREIGN KEY (ID_CARRO) REFERENCES CARROS(ID_CARRO)
);

(
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (1, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (2, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (3, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (4, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (5, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (6, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (7, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (8, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (9, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (10, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (11, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (12, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (13, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (14, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (15, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (16, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (17, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (18, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (19, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (20, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (21, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (22, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (23, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (24, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (25, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (26, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (27, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (28, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (29, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (30, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (31, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (32, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (33, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (34, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (35, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (36, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (37, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (38, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (39, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (40, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (41, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (42, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (43, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (44, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (45, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (46, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (47, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (48, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (49, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (50, 'Em manutenção');
-- Continuação abaixo ??


INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (51, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (52, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (53, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (54, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (55, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (56, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (57, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (58, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (59, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (60, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (61, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (62, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (63, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (64, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (65, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (66, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (67, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (68, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (69, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (70, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (71, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (72, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (73, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (74, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (75, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (76, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (77, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (78, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (79, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (80, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (81, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (82, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (83, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (84, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (85, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (86, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (87, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (88, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (89, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (90, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (91, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (92, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (93, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (94, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (95, 'Em manutenção');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (96, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (97, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (98, 'Disponível');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (99, 'Vendido');
INSERT INTO STATUS_CARRO (ID_CARRO, STATUS) VALUES (100, 'Em manutenção');



SELECT * FROM CARROS;

ALTER TABLE CARROS
ADD DATA_COMPRA DATE;


UPDATE CARROS SET DATA_COMPRA = TO_DATE('2021-03-15', 'YYYY-MM-DD') WHERE ID_CARRO = 1;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2022-07-22', 'YYYY-MM-DD') WHERE ID_CARRO = 2;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2023-01-10', 'YYYY-MM-DD') WHERE ID_CARRO = 3;
-- ... até o ID 100 ou mais

UPDATE CARROS SET DATA_COMPRA = TO_DATE('2016-04-12', 'YYYY-MM-DD') WHERE ID_CARRO = 1;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2018-07-21', 'YYYY-MM-DD') WHERE ID_CARRO = 2;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2020-01-30', 'YYYY-MM-DD') WHERE ID_CARRO = 3;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-09-10', 'YYYY-MM-DD') WHERE ID_CARRO = 4;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-12-05', 'YYYY-MM-DD') WHERE ID_CARRO = 5;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2021-03-15', 'YYYY-MM-DD') WHERE ID_CARRO = 6;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2015-06-22', 'YYYY-MM-DD') WHERE ID_CARRO = 7;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2023-02-28', 'YYYY-MM-DD') WHERE ID_CARRO = 8;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2022-11-17', 'YYYY-MM-DD') WHERE ID_CARRO = 9;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2016-08-08', 'YYYY-MM-DD') WHERE ID_CARRO = 10;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-10-19', 'YYYY-MM-DD') WHERE ID_CARRO = 11;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2020-04-23', 'YYYY-MM-DD') WHERE ID_CARRO = 12;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2018-05-14', 'YYYY-MM-DD') WHERE ID_CARRO = 13;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-01-27', 'YYYY-MM-DD') WHERE ID_CARRO = 14;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2021-07-04', 'YYYY-MM-DD') WHERE ID_CARRO = 15;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2015-03-03', 'YYYY-MM-DD') WHERE ID_CARRO = 16;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2022-12-12', 'YYYY-MM-DD') WHERE ID_CARRO = 17;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2016-06-09', 'YYYY-MM-DD') WHERE ID_CARRO = 18;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-08-29', 'YYYY-MM-DD') WHERE ID_CARRO = 19;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2023-05-16', 'YYYY-MM-DD') WHERE ID_CARRO = 20;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-11-02', 'YYYY-MM-DD') WHERE ID_CARRO = 21;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2020-09-21', 'YYYY-MM-DD') WHERE ID_CARRO = 22;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2018-03-10', 'YYYY-MM-DD') WHERE ID_CARRO = 23;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-12-15', 'YYYY-MM-DD') WHERE ID_CARRO = 24;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2021-04-08', 'YYYY-MM-DD') WHERE ID_CARRO = 25;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2016-10-20', 'YYYY-MM-DD') WHERE ID_CARRO = 26;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-02-28', 'YYYY-MM-DD') WHERE ID_CARRO = 27;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2022-07-07', 'YYYY-MM-DD') WHERE ID_CARRO = 28;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2015-05-19', 'YYYY-MM-DD') WHERE ID_CARRO = 29;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2023-03-25', 'YYYY-MM-DD') WHERE ID_CARRO = 30;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2020-06-11', 'YYYY-MM-DD') WHERE ID_CARRO = 31;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2018-08-14', 'YYYY-MM-DD') WHERE ID_CARRO = 32;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-01-23', 'YYYY-MM-DD') WHERE ID_CARRO = 33;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-09-09', 'YYYY-MM-DD') WHERE ID_CARRO = 34;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2021-11-30', 'YYYY-MM-DD') WHERE ID_CARRO = 35;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2016-12-17', 'YYYY-MM-DD') WHERE ID_CARRO = 36;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2022-02-20', 'YYYY-MM-DD') WHERE ID_CARRO = 37;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2015-08-06', 'YYYY-MM-DD') WHERE ID_CARRO = 38;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-04-28', 'YYYY-MM-DD') WHERE ID_CARRO = 39;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2020-10-19', 'YYYY-MM-DD') WHERE ID_CARRO = 40;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-06-15', 'YYYY-MM-DD') WHERE ID_CARRO = 41;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2021-01-08', 'YYYY-MM-DD') WHERE ID_CARRO = 42;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2018-11-11', 'YYYY-MM-DD') WHERE ID_CARRO = 43;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2016-07-25', 'YYYY-MM-DD') WHERE ID_CARRO = 44;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2015-03-14', 'YYYY-MM-DD') WHERE ID_CARRO = 45;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2023-06-02', 'YYYY-MM-DD') WHERE ID_CARRO = 46;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-09-17', 'YYYY-MM-DD') WHERE ID_CARRO = 47;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-05-27', 'YYYY-MM-DD') WHERE ID_CARRO = 48;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2020-08-23', 'YYYY-MM-DD') WHERE ID_CARRO = 49;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2022-03-29', 'YYYY-MM-DD') WHERE ID_CARRO = 50;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2015-12-04', 'YYYY-MM-DD') WHERE ID_CARRO = 51;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2018-09-18', 'YYYY-MM-DD') WHERE ID_CARRO = 52;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2021-07-25', 'YYYY-MM-DD') WHERE ID_CARRO = 53;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-02-06', 'YYYY-MM-DD') WHERE ID_CARRO = 54;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-10-31', 'YYYY-MM-DD') WHERE ID_CARRO = 55;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2020-05-19', 'YYYY-MM-DD') WHERE ID_CARRO = 56;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2016-01-14', 'YYYY-MM-DD') WHERE ID_CARRO = 57;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2022-11-09', 'YYYY-MM-DD') WHERE ID_CARRO = 58;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2015-07-30', 'YYYY-MM-DD') WHERE ID_CARRO = 59;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2018-04-21', 'YYYY-MM-DD') WHERE ID_CARRO = 60;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-01-11', 'YYYY-MM-DD') WHERE ID_CARRO = 61;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2020-07-29', 'YYYY-MM-DD') WHERE ID_CARRO = 62;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-06-03', 'YYYY-MM-DD') WHERE ID_CARRO = 63;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2021-03-12', 'YYYY-MM-DD') WHERE ID_CARRO = 64;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2016-09-22', 'YYYY-MM-DD') WHERE ID_CARRO = 65;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2018-12-01', 'YYYY-MM-DD') WHERE ID_CARRO = 66;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2015-11-16', 'YYYY-MM-DD') WHERE ID_CARRO = 67;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-08-26', 'YYYY-MM-DD') WHERE ID_CARRO = 68;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2022-02-05', 'YYYY-MM-DD') WHERE ID_CARRO = 69;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-04-15', 'YYYY-MM-DD') WHERE ID_CARRO = 70;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2020-10-07', 'YYYY-MM-DD') WHERE ID_CARRO = 71;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2018-05-20', 'YYYY-MM-DD') WHERE ID_CARRO = 72;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2016-03-02', 'YYYY-MM-DD') WHERE ID_CARRO = 73;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-09-28', 'YYYY-MM-DD') WHERE ID_CARRO = 74;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2021-06-15', 'YYYY-MM-DD') WHERE ID_CARRO = 75;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-12-11', 'YYYY-MM-DD') WHERE ID_CARRO = 76;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2015-05-07', 'YYYY-MM-DD') WHERE ID_CARRO = 77;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2020-02-22', 'YYYY-MM-DD') WHERE ID_CARRO = 78;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2018-10-17', 'YYYY-MM-DD') WHERE ID_CARRO = 79;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2016-08-30', 'YYYY-MM-DD') WHERE ID_CARRO = 80;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-03-13', 'YYYY-MM-DD') WHERE ID_CARRO = 81;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2021-01-28', 'YYYY-MM-DD') WHERE ID_CARRO = 82;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-07-09', 'YYYY-MM-DD') WHERE ID_CARRO = 83;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2022-04-01', 'YYYY-MM-DD') WHERE ID_CARRO = 84;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2015-10-19', 'YYYY-MM-DD') WHERE ID_CARRO = 85;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2018-06-24', 'YYYY-MM-DD') WHERE ID_CARRO = 86;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2020-12-05', 'YYYY-MM-DD') WHERE ID_CARRO = 87;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2016-02-14', 'YYYY-MM-DD') WHERE ID_CARRO = 88;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-11-30', 'YYYY-MM-DD') WHERE ID_CARRO = 89;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2021-08-20', 'YYYY-MM-DD') WHERE ID_CARRO = 90;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-05-26', 'YYYY-MM-DD') WHERE ID_CARRO = 91;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2023-03-12', 'YYYY-MM-DD') WHERE ID_CARRO = 92;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2016-07-08', 'YYYY-MM-DD') WHERE ID_CARRO = 93;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2018-01-15', 'YYYY-MM-DD') WHERE ID_CARRO = 94;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2020-09-29', 'YYYY-MM-DD') WHERE ID_CARRO = 95;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2015-04-20', 'YYYY-MM-DD') WHERE ID_CARRO = 96;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2019-07-11', 'YYYY-MM-DD') WHERE ID_CARRO = 97;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2021-11-04', 'YYYY-MM-DD') WHERE ID_CARRO = 98;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2017-03-27', 'YYYY-MM-DD') WHERE ID_CARRO = 99;
UPDATE CARROS SET DATA_COMPRA = TO_DATE('2022-05-18', 'YYYY-MM-DD') WHERE ID_CARRO = 100;

INSERT INTO COMPRA_CARRO (ID_CARRO, DATA_COMPRA) VALUES (100, TO_DATE('2022-05-18', 'YYYY-MM-DD'));
 SELECT * FROM CARROS ;
 
 
 
 
 