CREATE VIEW CARROS_CAROS AS 
SELECT ID_CARRO,MARCA,MODELO,ANO_FABRICACAO,PRECO 
FROM Carros
WHERE PRECO>70000;

CREATE VIEW CARROS_RECENTES AS 
SELECT ID_CARRO,MARCA,MODELO,ANO_FABRICACAO,PRECO 
FROM Carros
WHERE ANO_FABRICACAO> 2018;

CREATE VIEW RESUMO_VENDAS AS 
SELECT MARCA,MODELO , PRECO 
FROM Carros;

CREATE VIEW CARROS_ORDENADOS_POR_PRECO AS 
SELECT * FROM Carros 
ORDER BY PRECO DESC ;

SELECT VIEW_NAME FROM USER_VIEWS ;

SELECT TEXT FROM USER_VIEWS WHERE VIEW_NAME = 'CARROS_CAROS';

CREATE VIEW SOMA_VALOR_CARRO AS 
SELECT SUM(PRECO) AS TOTAL 
FROM Carros;



CREATE VIEW MEDIA_VALOR_CARRO AS
SELECT AVG (PRECO) AS MEDIA 
FROM Carros
select * from MEDIA_VALOR_CARRO
 select * from SOMA_VALOR_CARRO;


SELECT * FROM Carros

SELECT  MODELO FROM Carros
WHERE MODELO LIKE '%A%';


SELECT MODELO FROM Carros
WHERE MODELO LIKE '%MA%';

select initcap ('JoAO PeDrO FeRnAnDeS') as nome_formatado 
from dual;


select instr ('banana','a') as posicao from dual;


select length ('banana') as tamanho from dual;

select lower ('JoÃO PeDRo FERnAndes') as resultado from dual;

select upper ('joao pedro fernandes') as resultado from dual; 

select lpad ('45','5','0') as tamanho from dual ;

select substr ('joao pedro', '4','1') as resultado from dual;

select replace('banana','a','o') as resultado from dual ;

select round (123.456,2) as resultado from dual;

select trunc (123.456,2) as resultado from dual ;

select mod (10,3) as resultado from dual ;

select sysdate from dual ;

SELECT MONTHS_BETWEEN(TO_DATE('15-JUL-2025','DD-MON-YYYY'), TO_DATE('15-JAN-2025','DD-MON-YYYY')) AS meses_diff FROM dual;

select add_months(sysdate,3) as nova_data from dual

select next_day(sysdate,3)as proxima_segunda from dual ;

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY') AS data_formatada FROM dual;

SELECT TRIM('   João Pedro   ') AS nome_limpo FROM dual;

SELECT 'Olá, ' || 'João!' AS saudacao FROM dual;

-----------------------------------------------------

SELECT NVL(NULL, 'Sem valor') AS resultado FROM dual;
-- Resultado: 'Sem valor'

SELECT NVL('João', 'Sem valor') AS resultado FROM dual;
-- Resultado: 'João'

----------------------------------------------------------

SELECT NVL2(NULL, 'Tem valor', 'Está vazio') AS resultado FROM dual;
-- Resultado: 'Está vazio'

SELECT NVL2('João', 'Tem valor', 'Está vazio') AS resultado FROM dual;
-- Resultado: 'Tem valor'

---------------------------------------------------------

    
  
SELECT c.nome, p.produto
FROM clientes c, pedidos p
WHERE c.id_cliente = p.id_cliente;

SELECT COUNT(*) AS total_clientes
FROM clientes;


SELECT AVG(salario) AS media_salarial
FROM funcionarios;


SELECT MAX(preco) AS mais_caro
FROM produtos;


SELECT MIN(preco) AS mais_barato
FROM produtos;



SELECT SUM(valor_total) AS total_vendas
FROM vendas;


SELECT nome
FROM clientes
WHERE id_cliente IN (
    SELECT id_cliente
    FROM pedidos
    WHERE data_pedido >= TO_DATE('01-JAN-2025','DD-MON-YYYY')
);


SELECT nome
FROM produtos
WHERE categoria IN ('Eletrônico', 'Informática');



SELECT nome
FROM produtos
WHERE categoria NOT IN ('Eletrônico', 'Informática');


SELECT nome
FROM funcionarios
WHERE id_departamento IN (
    SELECT id_departamento
    FROM departamentos
    WHERE nome = 'TI'
);

INSERT INTO nome_tabela (coluna1, coluna2, ...)
VALUES (valor1, valor2, ...);

UPDATE nome_tabela
SET coluna1 = novo_valor1, coluna2 = novo_valor2
WHERE condição;


DELETE FROM nome_tabela
WHERE condição;




CREATE TABLE clientes (
  id_cliente NUMBER PRIMARY KEY,
  nome VARCHAR2(50)
);


CREATE TABLE pedidos (
  id_pedido NUMBER PRIMARY KEY,
  id_cliente NUMBER,
  FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
);


CREATE TABLE usuarios (
  id NUMBER PRIMARY KEY,
  email VARCHAR2(100) UNIQUE
);



CREATE TABLE produtos (
  id_produto NUMBER PRIMARY KEY,
  preco NUMBER CHECK (preco > 0)
);



CREATE TABLE funcionarios (
  id_func NUMBER PRIMARY KEY,
  nome VARCHAR2(50) NOT NULL
);


IF condição1 THEN
   -- código se for verdadeiro
ELSIF condição2 THEN
   -- outro código
ELSE
   -- código se nenhuma for verdadeira
END IF;



VARIABLE v_nome VARCHAR2(50)

BEGIN
  :v_nome := 'Maria';
END;
/

PRINT v_nome


DBMS_OUTPUT.PUT_LINE('Texto aqui');


set serverutput on ;

begin 
  dbms_output.put_line ('ola,mundo!');
  end;
  /
  
  
  select * from Carros ;
  (
  INSERT INTO carro (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (100, 'Ford', 'Modelo_100', 2000, 20000);
INSERT INTO carro (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (101, 'Chevrolet', 'Modelo_101', 2001, 21000);
INSERT INTO carro (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (102, 'Toyota', 'Modelo_102', 2002, 22000);
INSERT INTO carro (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (103, 'Honda', 'Modelo_103', 2003, 23000);
INSERT INTO carro (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (104, 'Volkswagen', 'Modelo_104', 2004, 24000);
INSERT INTO carro (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (105, 'Ford', 'Modelo_105', 2005, 25000);
INSERT INTO carro (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (106, 'Chevrolet', 'Modelo_106', 2006, 26000);
INSERT INTO carro (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (107, 'Toyota', 'Modelo_107', 2007, 27000);
INSERT INTO carro (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (108, 'Honda', 'Modelo_108', 2008, 28000);
INSERT INTO carro (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (109, 'Volkswagen', 'Modelo_109', 2009, 29000);
-- (continua seguindo esse padrão até o ID 299)
)
(
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (110, 'Ford', 'Modelo_110', 2010, 20000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (111, 'Chevrolet', 'Modelo_111', 2011, 21000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (112, 'Toyota', 'Modelo_112', 2012, 22000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (113, 'Honda', 'Modelo_113', 2013, 23000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (114, 'Volkswagen', 'Modelo_114', 2014, 24000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (115, 'Ford', 'Modelo_115', 2015, 25000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (116, 'Chevrolet', 'Modelo_116', 2016, 26000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (117, 'Toyota', 'Modelo_117', 2017, 27000);
INSERT INTO Carros(ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (118, 'Honda', 'Modelo_118', 2018, 28000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (119, 'Volkswagen', 'Modelo_119', 2019, 29000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (120, 'Ford', 'Modelo_120', 2020, 30000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (121, 'Chevrolet', 'Modelo_121', 2021, 31000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (122, 'Toyota', 'Modelo_122', 2022, 32000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (123, 'Honda', 'Modelo_123', 2000, 33000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (124, 'Volkswagen', 'Modelo_124', 2001, 34000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (125, 'Ford', 'Modelo_125', 2002, 35000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (126, 'Chevrolet', 'Modelo_126', 2003, 36000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (127, 'Toyota', 'Modelo_127', 2004, 37000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (128, 'Honda', 'Modelo_128', 2005, 38000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (129, 'Volkswagen', 'Modelo_129', 2006, 39000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (130, 'Ford', 'Modelo_130', 2007, 40000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (131, 'Chevrolet', 'Modelo_131', 2008, 41000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (132, 'Toyota', 'Modelo_132', 2009, 42000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (133, 'Honda', 'Modelo_133', 2010, 43000);
INSERT INTO Carros(ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (134, 'Volkswagen', 'Modelo_134', 2011, 44000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (135, 'Ford', 'Modelo_135', 2012, 45000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (136, 'Chevrolet', 'Modelo_136', 2013, 46000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (137, 'Toyota', 'Modelo_137', 2014, 47000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (138, 'Honda', 'Modelo_138', 2015, 48000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (139, 'Volkswagen', 'Modelo_139', 2016, 49000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (140, 'Ford', 'Modelo_140', 2017, 50000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (141, 'Chevrolet', 'Modelo_141', 2018, 51000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (142, 'Toyota', 'Modelo_142', 2019, 52000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (143, 'Honda', 'Modelo_143', 2020, 53000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (144, 'Volkswagen', 'Modelo_144', 2021, 54000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (145, 'Ford', 'Modelo_145', 2022, 55000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (146, 'Chevrolet', 'Modelo_146', 2000, 56000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (147, 'Toyota', 'Modelo_147', 2001, 57000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (148, 'Honda', 'Modelo_148', 2002, 58000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (149, 'Volkswagen', 'Modelo_149', 2003, 59000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (150, 'Ford', 'Modelo_150', 2004, 60000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (151, 'Chevrolet', 'Modelo_151', 2005, 61000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (152, 'Toyota', 'Modelo_152', 2006, 62000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (153, 'Honda', 'Modelo_153', 2007, 63000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (154, 'Volkswagen', 'Modelo_154', 2008, 64000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (155, 'Ford', 'Modelo_155', 2009, 65000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (156, 'Chevrolet', 'Modelo_156', 2010, 66000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (157, 'Toyota', 'Modelo_157', 2011, 67000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (158, 'Honda', 'Modelo_158', 2012, 68000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (159, 'Volkswagen', 'Modelo_159', 2013, 69000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (160, 'Ford', 'Modelo_160', 2014, 20000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (161, 'Chevrolet', 'Modelo_161', 2015, 21000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (162, 'Toyota', 'Modelo_162', 2016, 22000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (163, 'Honda', 'Modelo_163', 2017, 23000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (164, 'Volkswagen', 'Modelo_164', 2018, 24000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (165, 'Ford', 'Modelo_165', 2019, 25000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (166, 'Chevrolet', 'Modelo_166', 2020, 26000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (167, 'Toyota', 'Modelo_167', 2021, 27000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (168, 'Honda', 'Modelo_168', 2022, 28000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (169, 'Volkswagen', 'Modelo_169', 2000, 29000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (170, 'Ford', 'Modelo_170', 2001, 30000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (171, 'Chevrolet', 'Modelo_171', 2002, 31000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (172, 'Toyota', 'Modelo_172', 2003, 32000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (173, 'Honda', 'Modelo_173', 2004, 33000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (174, 'Volkswagen', 'Modelo_174', 2005, 34000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (175, 'Ford', 'Modelo_175', 2006, 35000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (176, 'Chevrolet', 'Modelo_176', 2007, 36000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (177, 'Toyota', 'Modelo_177', 2008, 37000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (178, 'Honda', 'Modelo_178', 2009, 38000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (179, 'Volkswagen', 'Modelo_179', 2010, 39000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (180, 'Ford', 'Modelo_180', 2011, 40000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (181, 'Chevrolet', 'Modelo_181', 2012, 41000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (182, 'Toyota', 'Modelo_182', 2013, 42000);
INSERT INTO Carros(ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (183, 'Honda', 'Modelo_183', 2014, 43000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (184, 'Volkswagen', 'Modelo_184', 2015, 44000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (185, 'Ford', 'Modelo_185', 2016, 45000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (186, 'Chevrolet', 'Modelo_186', 2017, 46000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (187, 'Toyota', 'Modelo_187', 2018, 47000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (188, 'Honda', 'Modelo_188', 2019, 48000);
INSERT INTO Carros(ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (189, 'Volkswagen', 'Modelo_189', 2020, 49000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (190, 'Ford', 'Modelo_190', 2021, 50000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (191, 'Chevrolet', 'Modelo_191', 2022, 51000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (192, 'Toyota', 'Modelo_192', 2000, 52000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (193, 'Honda', 'Modelo_193', 2001, 53000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (194, 'Volkswagen', 'Modelo_194', 2002, 54000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (195, 'Ford', 'Modelo_195', 2003, 55000);
INSERT INTO Carros (ID_CARRO, MARCA, MODELO, ANO_FABRICACAO, PRECO) VALUES (196, 'Chevrolet', 'Modelo_196', 2004, 56000);
)
SELECT* FROM Carros;
 
 SELECT * FROM Carros
ORDER BY PRECO desc;  -- ou DESC

SELECT * FROM Carros
ORDER BY ID_CARRO ASC;


select *
from Carros 
where PRECO < 25000;