create table PLASTCOR (
ID_EMPRESA     NUMBER PRIMARY KEY ,
NOME           VARCHAR2(100)NOT NULL,
CNPJ           VARCHAR2 (18)UNIQUE NOT NULL,
INSCRICAO_ESTADUAL VARCHAR2(20),
DATA_ABERTURA DATE,
RAMO_ATIVIDADE VARCHAR2 (50),
TELEFONE       VARCHAR2 (15),
EMAIL          VARCHAR2 (100),
ENDERECO       VARCHAR2 (150),
CIDADE         VARCHAR2 (50),
ESTADO         VARCHAR2 (2),
STATUS_ATUAL   VARCHAR2 (20)DEFAULT 'ATIVA'
);

RENAME PLASTCOR TO HINO;

SELECT * FROM HINO ;

INSERT INTO HINO (
  ID_EMPRESA, NOME, CNPJ, INSCRICAO_ESTADUAL, DATA_ABERTURA, RAMO_ATIVIDADE,
  TELEFONE, EMAIL, ENDERECO, CIDADE, ESTADO, STATUS_ATUAL
) VALUES (
  1, 'PLASTICOR ', '12.345.678/0001-90', '1234567890', TO_DATE('10/01/2010', 'DD/MM/YYYY'),
  'Tecnologia', '(11) 99999-0001', 'contato@techvision.com.br', 'Rua criatiano greve 281', 'limeira', 'SP', 'ATIVA'
);

INSERT INTO HINO VALUES (
  2, 'DIZENP', '98.765.432/0001-55', '9876543210', TO_DATE('23/03/2015', 'DD/MM/YYYY'),
  'Meio Ambiente', '(21) 98888-2222', 'contato@ecovida.com', 'Av. Verde, 45', 'Rio de Janeiro', 'RJ', 'ATIVA'
);

INSERT INTO HINO VALUES (
  3, 'G3', '45.678.123/0001-12', '456123789', TO_DATE('15/05/2005', 'DD/MM/YYYY'),
  'Engenharia Civil', '(31) 97777-3333', 'contato@construmax.com.br', 'Rua Concreto, 300', 'Belo Horizonte', 'MG', 'ATIVA'
);

INSERT INTO HINO VALUES (
  4, 'BIOMETAL', '33.222.111/0001-80', '1122334455', TO_DATE('01/11/2012', 'DD/MM/YYYY'),
  'Farmacêutica', '(41) 96666-4444', 'contato@farmatec.com.br', 'Rua da Saúde, 200', 'Curitiba', 'PR', 'INATIVA'
);

INSERT INTO HINO VALUES (
  5, 'IRBAS', '77.888.999/0001-10', '9988776655', TO_DATE('08/08/2018', 'DD/MM/YYYY'),
  'Educação', '(51) 95555-6666', 'contato@educamais.com.br', 'Rua do Saber, 1200', 'Porto Alegre', 'RS', 'ATIVA'
);

SELECT* FROM HINO ;

ALTER TABLE HINO 
ADD TOTAL_FUCIONARIO VARCHAR2(1000);


UPDATE HINO 
SET TOTAL_FUCIONARIO = 987
WHERE  ID_EMPRESA =1;

UPDATE HINO 
SET TOTAL_FUCIONARIO = 854
WHERE  ID_EMPRESA =2;

UPDATE HINO 
SET TOTAL_FUCIONARIO = 341
WHERE  ID_EMPRESA =3;

UPDATE HINO 
SET TOTAL_FUCIONARIO = 965
WHERE  ID_EMPRESA =4;

UPDATE HINO 
SET TOTAL_FUCIONARIO = 467
WHERE  ID_EMPRESA =5;

SELECT * FROM HINO;

UPDATE HINO
SET RAMO_ATIVIDADE = 'EMPRESA DE PLASTICO'
WHERE ID_EMPRESA = 1;

UPDATE HINO
SET RAMO_ATIVIDADE = 'PNEU'
WHERE ID_EMPRESA = 2;

UPDATE HINO
SET RAMO_ATIVIDADE = 'CONTABILIDADE'
WHERE ID_EMPRESA = 3;

UPDATE HINO
SET RAMO_ATIVIDADE = 'TECNOLOGIA CIRÚRGICOS'
WHERE ID_EMPRESA = 4;

UPDATE HINO
SET RAMO_ATIVIDADE = 'INDUSTRIA AUTOMOTIVA'
WHERE ID_EMPRESA = 5;

ALTER TABLE HINO 
ADD FATURAMENTO NUMBER (10,2);


(
UPDATE HINO
SET FATURAMENTO =365263.25 
WHERE ID_EMPRESA =1;

SELECT * FROM HINO;

UPDATE HINO
SET FATURAMENTO =369

UPDATE HINO
SET FATURAMENTO =265560.85
WHERE ID_EMPRESA =3;

UPDATE HINO
SET FATURAMENTO =745745.36 
WHERE ID_EMPRESA =4;

UPDATE HINO
SET FATURAMENTO =265984.69 
WHERE ID_EMPRESA =5;
 

SELECT '265' || ',' || '984' || ',' || '69' AS resultado FROM dual;

SELECT '745' || ',' || '587' || ',' || '36' AS resultado FROM dual;

SELECT '265' || ',' || '560' || ',' || '85' AS resultado FROM dual;

SELECT '369' || ',' || '825' || ',' || '52' AS resultado FROM dual;

SELECT '365' || ',' || '263' || ',' || '25' AS resultado FROM dual;

SELECT * FROM HINO;
)


UPDATE HINO
SET EMAIL = 'contato@plastcor.com.br'
WHERE ID_EMPRESA= 1 ;

UPDATE HINO
SET EMAIL = 'contato@dixenp.com.br'
WHERE ID_EMPRESA= 2 ;

UPDATE HINO
SET EMAIL = 'contato@g3.com.br'
WHERE ID_EMPRESA= 3 ;

UPDATE HINO
SET EMAIL = 'contato@biometal.com.br'
WHERE ID_EMPRESA= 4 ;

UPDATE HINO
SET EMAIL = 'contato@irbas.com.br'
WHERE ID_EMPRESA= 5 ;

select * from HINO;

CREATE INDEX idx_empresa_cnpj
ON HINO (CNPJ);

SELECT * FROM HINO ;

SELECT NOME FROM HINO 
WHERE NOME LIKE '%P%';

SELECT NOME FROM HINO 
WHERE NOME LIKE '%IR%' AND EMAIL  LIKE'%contato%';




