CREATE TABLE FORNECEDORES (
ID_FORNECEDOR NUMBER PRIMARY KEY,
NOME VARCHAR2(50),
CNPJ VARCHAR2(20),
TELEFONE VARCHAR2(20)
);

CREATE TABLE CATEGORIAS(
ID_CATEGORIA NUMBER PRIMARY KEY,
NOME VARCHAR2(30)
);

CREATE TABLE PRODUTOS (
  ID_PRODUTO NUMBER PRIMARY KEY,
  NOME VARCHAR2(50),
  PRECO NUMBER(10, 2),
  VALIDADE DATE,
  ESTOQUE NUMBER,
  ID_FORNECEDOR NUMBER,
  FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR)
);

CREATE TABLE PRODUTOS_CATEGORIA (
  ID_PRODUTO NUMBER,
  ID_CATEGORIA NUMBER,
  PRIMARY KEY (ID_PRODUTO, ID_CATEGORIA),
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
  FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

INSERT INTO FORNECEDORES VALUES (1,'Nestlé','12.345.678/0001=90','(11)4002=8922'); 
INSERT INTO FORNECEDORES VALUES (2, 'Coca-Cola', '98.765.432/0001-10', '(21) 1234-5678');

INSERT INTO CATEGORIAS VALUES (1, 'Bebidas');
INSERT INTO CATEGORIAS VALUES (2, 'Doces');
INSERT INTO CATEGORIAS VALUES (3, 'Laticínios');

INSERT INTO PRODUTOS VALUES (100, 'Leite Integral', 4.99, TO_DATE('30/08/2025','DD/MM/YYYY'), 200, 1);
INSERT INTO PRODUTOS VALUES (101, 'Coca-Cola 2L', 7.50, TO_DATE('15/09/2025','DD/MM/YYYY'), 150, 2);
INSERT INTO PRODUTOS VALUES (102, 'Chocolate ao leite', 3.75, TO_DATE('01/12/2025','DD/MM/YYYY'), 100, 1);

INSERT INTO PRODUTOS_CATEGORIA VALUES (100, 3); -- Leite ? Laticínios
INSERT INTO PRODUTOS_CATEGORIA VALUES (101, 1); -- Coca-Cola ? Bebidas
INSERT INTO PRODUTOS_CATEGORIA VALUES (102, 2);


CREATE VIEW PRODUTOS_VENCIMENTO AS
SELECT NOME, VALIDADE, ESTOQUE
FROM PRODUTOS
WHERE VALIDADE <= SYSDATE + 30;


SELECT 
  P.NOME AS PRODUTO,
  C.NOME AS CATEGORIA,
  F.NOME AS FORNECEDOR
FROM PRODUTOS P
JOIN PRODUTOS_CATEGORIA PC ON P.ID_PRODUTO = PC.ID_PRODUTO
JOIN CATEGORIAS C ON PC.ID_CATEGORIA = C.ID_CATEGORIA
JOIN FORNECEDORES F ON P.ID_FORNECEDOR = F.ID_FORNECEDOR;





