 CREATE TABLE LOJA_ONLINE(
 USUARIO VARCHAR2 (20),
 PRODUTOS VARCHAR2(30),
 COMPRAS  NUMBER,
 CARRINHO VARCHAR2(50),
 AVALIACOES VARCHAR2(100)
 );
 SELECT * FROM LOJA_ONLINE;
 
 INSERT INTO LOJA_ONLINE (USUARIO,PRODUTOS,COMPRAS,CARRINHO,AVALIACOES)
 VALUES ('JOAO PEDRO','COMPUTADOR GAMER',1,'FONE DE OUVIDO',5.2);
 
 INSERT INTO LOJA_ONLINE (USUARIO, PRODUTOS, COMPRAS, CARRINHO, AVALIACOES)
VALUES ('MARIA LIMA', 'SMARTPHONE', 2, 'CAPINHA DE CELULAR', '4.5');

INSERT INTO LOJA_ONLINE (USUARIO, PRODUTOS, COMPRAS, CARRINHO, AVALIACOES)
VALUES ('CARLOS EDUARDO', 'NOTEBOOK DELL', 1, 'MOCHILA', '5.0');

INSERT INTO LOJA_ONLINE (USUARIO, PRODUTOS, COMPRAS, CARRINHO, AVALIACOES)
VALUES ('ANA CLARA', 'TV 50 POLEGADAS', 1, 'SUPORTE DE PAREDE', '4.8');

INSERT INTO LOJA_ONLINE (USUARIO, PRODUTOS, COMPRAS, CARRINHO, AVALIACOES)
VALUES ('FERNANDO SOUZA', 'PS5', 1, 'CONTROLE EXTRA', '4.9');

INSERT INTO LOJA_ONLINE (USUARIO, PRODUTOS, COMPRAS, CARRINHO, AVALIACOES)
VALUES ('JULIA MENDES', 'TABLET SAMSUNG', 1, 'FONE BLUETOOTH', '4.3');

INSERT INTO LOJA_ONLINE (USUARIO, PRODUTOS, COMPRAS, CARRINHO, AVALIACOES)
VALUES ('RAFAEL SILVA', 'CADEIRA GAMER', 2, 'ALMOFADA LOMBAR', '5.0');

INSERT INTO LOJA_ONLINE (USUARIO, PRODUTOS, COMPRAS, CARRINHO, AVALIACOES)
VALUES ('LARISSA COSTA', 'ALEXA ECHO DOT', 1, 'LÂMPADA INTELIGENTE', '4.7');

INSERT INTO LOJA_ONLINE (USUARIO, PRODUTOS, COMPRAS, CARRINHO, AVALIACOES)
VALUES ('GABRIEL SANTOS', 'MONITOR 27"', 1, 'SUPORTE DE MESA', '4.6');

INSERT INTO LOJA_ONLINE (USUARIO, PRODUTOS, COMPRAS, CARRINHO, AVALIACOES)
VALUES ('THAIS OLIVEIRA', 'IMPRESSORA HP', 1, 'CARTUCHO DE TINTA', '4.4');

INSERT INTO LOJA_ONLINE (USUARIO,PRODUTOS,COMPRAS,CARRINHO,AVALIACOES) 
VALUES ('THAIS CARLA','COMEDOR OUTOMATICO',1,'DISGESTOR 3000','1.0');

INSERT INTO LOJA_ONLINE(USUARIO,PRODUTOS,COMPRAS,CARRINHO,AVALIACOES)
VALUES ('SEU JORGE','VIOLAO',1,'VIOLA','6.5');

INSERT INTO LOJA_ONLINE(USUARIO,PRODUTOS,COMPRAS,CARRINHO,AVALIACOES)
VALUES ('MC NEGAO ORIGINAL','KIT DA LACOSTE',1,'CORDAO DE OURO E DIAMANTE','10.0');


SELECT * FROM LOJA_ONLINE;

